create table if not exists public.report_states (
    id bigint generated by default as identity primary key,
    report_type text not null check (report_type in ('weekly', 'monthly')),
    period_start date not null,
    payload jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    unique (report_type, period_start)
);

alter table public.report_states enable row level security;

grant select, insert, update, delete on public.report_states to service_role;
grant usage, select on sequence public.report_states_id_seq to service_role;

-- Streamlit Secrets의 service_role 키로 서버에서만 접근합니다.
-- anon 사용자에게 공개 정책을 만들지 마세요.
